slug: apples
visit: visitn
charts:
- chart: gender
  title: Sex
- chart: ethnicity
  title: Ethnicity
webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://staging.partners.org/sleepdata.org
